### ISSUE TITLE
Account for all Socrata API endpoints

### ISSUE THREAD

**Issue by andrewbt** [CityOfPhiladelphia/soda-carto#20]
and ensure we have Lambda functions for handling them.

- [x] `/resource/xxxx-xxxx.json` (primary API endpoint)
- [x] `/resource/xxxx-xxxx.geojson`
- [x] `/api/views/xxxx-xxxx/rows.csv?accessType=DOWNLOAD` (all CSV endpoints are like
  this)
- [x] `/views/xxxx-xxxx/rows.json` (only 6 endpoints advertised this way)
- [x] `/views/xxxx-xxxx/rows.geojson`
- [ ] `/view/yyyy-yyyy` (DataLens page - note 4x4 is different from dataset id)

5 different endpoints for Socrata URLS
- 2 for a CSV
- some other ways for SoQL
- need to make sure that we are accomodating these API endpoints in the proxy

**Comment by timwis** [comment]
Hopefully we can support all of them from within one function. Though we may have to get a little clever (hacky) with the way we're parsing the dataset and format, since AWS API Gateway is pretty strict about params in URLs.
