### ISSUE TITLE
Dataset lookup table

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/soda-carto#8]
A way to map Socrata dataset IDs (ie `s98w-oiup`) to carto table names (ie. `phl.crime_incidents`) so that incoming queries can reference the socrata ID but pull from a carto table.

I'm thinking a YAML file may be the best option for this.

**Comment by andrewbt** [comment]
Or we could have a table in the Carto account! Would require overhead of an additional HTTP request, but would make it easy to update.

**Comment by timwis** [comment]
Yeah, that's true. I imagine that once this is in place, it won't ever change unless we made a mistake/typo though, so it may not be necessary to have easy update.
